name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.15.1"

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Export static site
        run: npm run build

      - name: Configure Git user
        run: |
          git config --global user.name "Jenna Tripoli"
          git config --global user.email "jennatripoli02@gmail.com"

      - name: Deploy to GitHub Pages
        run: |
          npm install --save-dev gh-pages
          npx gh-pages -d out
        env:
          PA_TOKEN: ${{ secrets.PA_TOKEN }}
